name: Suggestion
description: Submit an idea that may get added to Extrack.
title: "Suggestion: "
labels: ["idea", "suggestion"]
body:
  - type: textarea
    id: description
    attributes:
      label: 💡 A description of the suggestion
      description: Tell us what you would love to see in the newest Extrack update!
      placeholder: Enter the suggestion here.
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: 🚦 How urgent would this suggestion be?
      description: Tell us how urgent your suggestion would be.
      placeholder: Tell us how urgent it is. E.g. high priority, medium priority, low priority.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: ⭕ Is this suggestion related to an issue?
      description: Tell us if the suggestion is related to an issue, if yes, provide the issue link.
      placeholder: "Enter the issue link if it's related here."
    validations:
      required: false
